### ISSUE TITLE
Running install again does not do anything

### ISSUE THREAD

**Issue by reckart** [ltl-ude/inceptalytics#2]
I am having trouble installing the tool using the `./install` script (maybe due to https://github.com/numpy/numpy/issues/17807). The  install is taking ages and producing lots of errors. So I used CTRL-C to abort the install and changed the numpy version in the requiresments file from 1.20 to 1.21.

But then running `./install` again didn't do anything.

I would have expected that running the script again would restart the broken install or alternatively update the partial install. At least maybe a message saying something like "It looks like you have already installed inception-analytics. If you want to reinstall, please delete the `env` folder and re-run the script" or something like that.

**Comment by simulacrum6** [comment]
The install script is no longer relevant since 21d7da7d534dd46a943c3b10d8be1569203a519c. The package can now be installed using pip.
