### ISSUE TITLE
Install script installs software outside venv

### ISSUE THREAD

**Issue by reckart** [ltl-ude/inceptalytics#3]
The install script upgrades pip and installs virtualenv before creating a virtualenv. That means, it may make changes to the users setup outside of the virtual env. I think it would be better to leave the general setup to the user and limit any changes of the script to happen within the virtual env.

**Comment by simulacrum6** [comment]
The install script is no longer relevant since 21d7da7d534dd46a943c3b10d8be1569203a519c. The package can now be installed using pip.
